sudo: required
services:
    - docker

before_install:
    - docker build -t pbadgujarns/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true pbadgujarns/docker-react npm run test -- --coverage 