sudo: required
services:
    - docker

before_install:
    - docker build -t pbadgujarns/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true pbadgujarns/docker-react npm run test -- --coverage 

deploy:
    provider: elasticbeanstalk 
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-721357086872"
    bucket_path: "docker-react"
    on:
        branch: master 
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

       


# http://dockerreact-env.eba-rp5hfcys.us-west-2.elasticbeanstalk.com/